
# https://github.com/djpnewton/zap_app
# using FFI, Clipboard, URL launcher.





LIB_NAME=zap_app
LIB=github.com/djpnewton/$(LIB_NAME)
LIB_BRANCH=master
LIB_FSPATH=$(GOPATH)/src/$(LIB)


#SAMPLE=keyboard_event
#SAMPLE=mousebuttons
SAMPLE=plugin_tutorial
#SAMPLE=pointer_demo
#SAMPLE=stocks
#SAMPLE=xbox_controller
$(SAMPLE_FSPATH)=$(LIB_FSPATH)/$(SAMPLE)





