# packing helper
# until its in hover etc

print:
	@echo Utils for packaging go-flutter.

win-init:
	# Icons
	# https://github.com/go-flutter-desktop/go-flutter/issues/156#issuecomment-527563054
	# https://gitlab.com/gozoo/rc-demo

	# run this from where the pubspec.yaml

	# copy files into /go/cmd
	cp ./main.exe.manifest $(HOME)/go/cmd
	cp ./main.rc $(HOME)/go/cmd
